version: "3"
services:
  node-app:
    build: .
    restart: always
    ports:
      - "80:1337"
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: