version: "3"
services:
  mongodb:
    image: mongo
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - new_db:/data/db
  node-app:
    build: .
    restart: always
    ports:
      - "80:3000"
    volumes:
      - .:/home/app/
      - /node_modules
    depends_on:
      - mongodb
volumes:
  new_db: