### Endpoint -> Register user account
POST http://localhost/api/register
content-type: application/json

{
    "email": "example@example.com",
    "password": "zaq1@WSX"
}

### Login -> Login user
POST http://localhost/api/login
content-type: application/json

{
    "email": "example@example.com",
    "password": "zaq1@WSX"
}

### Endpoint -> Fetch code fragments
@token = JWT_TOKEN
POST http://localhost/api/codefragments
content-type: application/json
Authorization: Bearer {{token}}

{
   "tag": "Java",
   "searchPhrase": "int",
   "amount": 2
}